FROM pspdev/pspdev:latest AS main_builder
WORKDIR /app

COPY . .

RUN psp-cmake -B build/psp -S . && make -C build/psp -j $(nproc)

FROM scratch AS exporter

COPY --from=main_builder /app/build/psp/scratch-psp.zip /
